################################################################################
#
# electricity kwh price
#
################################################################################

- platform: template
  sensors:
    electricity_kwh_unit_price:
      friendly_name_template: "Electricity Unit Price"
      value_template: "0.3879"
      unit_of_measurement: "£/kWh"