id: '01f4c141-2750-459a-a547-49452d30b344'
alias: Remote Remotec Bedroom 1 Press Button Eight 1x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "008"
      value: "KeyPressed"
condition: []
action:
  - service: light.toggle
    data:
      entity_id:
        - light.bedroom_1_lamp_1
mode: single