id: '07bee00a-5e6b-40e0-a2d5-cebde2338263'
alias: Remotec Bedroom 1 Press Button Four 1x
description: ""
initial_state: true
mode: single
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "004"
      value: "KeyPressed"
condition: []
action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.bedroom_1_led_strip