id: '1773d4ec-a438-45cb-bcc1-64d3f6e9cb94'
alias: Remote Remotec Bedroom 1 Press Button Five 1x
description: ""
initial_state: true
mode: single
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "005"
      value: "KeyPressed"
condition: []
action:
  - service: fan.toggle
    data: {}
    target:
      entity_id: fan.sonoff_1000cc2f24