id: '605778b8-e2b0-4b7c-bad7-605165309578'
alias: Remotec Bedroom 1 Press Button Two 1x
description: ""
initial_state: true
mode: single
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "002"
      value: "KeyPressed"
condition: []
action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.bedroom_1_bedside_fan_plug