id: '40c5054f-dc30-47d6-a153-12a647cf800c'
alias: Remotec Bedroom 1 Press Button Seven 1x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "007"
      value: "KeyPressed"
condition: []
action:
  - service: light.toggle
    data:
      entity_id:
        - light.bedroom_1_lamp_2
mode: single
