id: '88d6d53c-d880-40ee-851d-2c4aca100298'
alias: Remote Remotec Bedroom 1 Press Button One 1x
description: ""
initial_state: true
mode: single
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "001"
      value: "KeyPressed"
condition: []
action:
  - service: light.toggle
    data:
      transition: 1
    target:
      entity_id: light.bedroom_1_light