id: '2f76ec81-19cf-427b-972c-2c4c7c360cab'
alias: Remote Remotec Bedroom 1 Press Button Six 1x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "006"
      value: "KeyPressed"
condition: []
action:
  - service: cover.toggle
    data: {}
    target:
      entity_id: cover.bedroom_1_blind
mode: single
