id: '2be41342-c349-46b1-a276-77b96b4ef0d6'
alias: Remotec Bedroom 1 Press Button Three 2x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "003"
      value: "KeyHeldDown"
condition: []
action:
  - service: light.toggle
    data:
      entity_id:
        - light.bedroom_1_lamp_2
mode: single