id: 'd982c1c2-351e-47f4-ad86-20ed3b5aecf0'
alias: Remotec Bedroom 1 Press Button Three 1x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "1da9e491b068a3646da5c3398a8da391"
      property_key: "003"
      value: "KeyPressed"
condition: []
action:
  - service: light.toggle
    data:
      entity_id:
        - light.bedroom_1_lamp_1
        - light.bedroom_1_lamp_2
mode: single