id: '9d21601f-bc1e-4609-882e-628f30a4d7bf'
alias: Media Living Room Kodi Play
initial_state: true
trigger:
  - entity_id: media_player.livingroom
    for: '00:00:02'
    platform: state
    to: playing
condition: []
action:
  - service: light.turn_off
    data:
      entity_id:
        - light.livingroom_lamp
        - light.livingroom_tv_led_strip
      transition: 2
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
        - switch.livingroom_1_light_switch
        - switch.livingroom_2_light_switch
        - switch.livingroom_surge_protector_mss426_christmas_candles_plug
mode: single