id: 'a97942cb-344a-4293-ad9d-2744d473ca77'
alias: Media Living Room Kodi Stop
initial_state: on
trigger:
  - entity_id: media_player.livingroom
    platform: state
    for: '00:00:04'
    from: playing
    to: idle
condition:
  - condition: state
    entity_id: input_boolean.home_night
    state: 'on'
action:
  - service: lifx.set_state
    data:
      power: true
      brightness: 226
      transition: 2
    target:
      entity_id: light.livingroom_lamp
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
        - switch.livingroom_surge_protector_mss426_christmas_candles_plug
  - service: climate.set_preset_mode
    data:
      preset_mode: "none"
    target:
      entity_id: climate.living_room
mode: single