id: '9d21601f-bc1e-4609-882e-628f30a4d7bf'
alias: Media Living Room Kodi Play
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - media_player.livingroom
    to: playing
    for:
      hours: 0
      minutes: 0
      seconds: 2
condition:
  - condition: state
    entity_id: input_boolean.home_night
    state: "on"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ states.media_player.livingroom.attributes.media_content_type == "movie" }}'
        sequence:
          - service: light.turn_off
            data:
              transition: 2
            target:
              entity_id:
                - light.livingroom_lamp
                - light.livingroom_tv_led_strip
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.livingroom_1_light_switch
                - switch.livingroom_2_light_switch
                - switch.livingroom_surge_protector_mss426_christmas_candles_plug
          - service: climate.set_preset_mode
            data:
              preset_mode: activity
            target:
              entity_id: climate.living_room
      - conditions:
          - condition: template
            value_template: '{{ states.media_player.livingroom.attributes.media_content_type == "tvshow" }}'
        sequence:
          - service: lifx.set_state
            data:
              brightness: 26
            target:
              entity_id:
                - light.livingroom_lamp
                - light.livingroom_tv_led_strip