id: 26a82b0e-d321-4aac-9fb5-4b9a8fe99e36
alias: Climate Toilet Open
initial_state: true
trigger:
  - platform: state
    entity_id:
    - binary_sensor.door_window_sensor_7_window_door_is_open_2
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition:
  - condition: state
    entity_id: switch.heating_control_switch
    state: 'on'
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_7_window_door_is_open_2
        state: 'on'
      sequence:
      - service: switch.turn_off
#        data: {}
        target:
          entity_id: switch.heating_toilet_control_switch
    - conditions:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_7_window_door_is_open_2
        state: 'off'
      sequence:
      - service: switch.turn_on
#        data: {}
        target:
          entity_id: switch.heating_toilet_control_switch
mode: single