id: '3bafb9dc-dd3a-4cba-9965-260c85493a7c'
alias: Climate Toilet Radiator Schedule
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type:
      - automation_reloaded
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id: 
      - climate.toilet
    to: "heat"
  - platform: state
    entity_id:
      - input_number.heating_minimum
      - input_number.heating_maximum
  - platform: state
    entity_id:
      - climate.toilet
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.toilet
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.toilet
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.toilet
action:
  - choose:
      - conditions:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ now().hour in [7, 17, 18, 19, 20, 21] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {{ states('input_number.heating_minimum')| float(0) }}
            target:
              entity_id: climate.toilet
      - conditions:
          - condition: template
            value_template: "{{ now().hour in [7, 17, 18, 19, 20, 21] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {{ states('input_number.heating_maximum')| float(0) }}
            target:
              entity_id: climate.toilet