id: '3bafb9dc-dd3a-4cba-9965-260c85493a7c'
alias: Climate Toilet Radiator Schedule
initial_state: true
trigger:
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id: switch.heating_toilet_control_switch
    to: "on"
  - platform: state
    entity_id:
      - input_number.heating_minimum
      - input_number.heating_average
      - input_number.heating_maximum
      - input_boolean.home_away
condition:
  - condition: state
    entity_id: switch.heating_toilet_control_switch
    state: "on"
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.home_away
        state: "off"
      sequence:
        - service: climate.set_temperature
          data_template:
            entity_id: climate.tado_smart_radiator_thermostat_va1993674240
            temperature: >
              {% if now().hour in [8, 9, 10, 11, 12, 13 ,14 ,15, 16, 17, 20, 21] %}
                {{ states('input_number.heating_average')| float(0) }}
              {% elif now().hour in [7, 18, 19] %}
                {{ states('input_number.heating_maximum')| float(0) }}
              {% else %}
                {{ states('input_number.heating_minimum')| float(0) }}
              {% endif %}
    - conditions:
      - condition: state
        entity_id: input_boolean.home_away
        state: "on"
      sequence:
        - service: climate.set_temperature
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va1993674240
            temperature: 5
    default: []
mode: single 