id: "3bafb9dc-dd3a-4cba-9965-260c85493a7c"
alias: "Climate Toilet Radiator Schedule"
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - schedule.toilet_thermostat_schedule
  - platform: state
    entity_id: 
      - climate.toilet
    to: "heat"
  - platform: state
    entity_id:
      - sensor.heating_min
      - sensor.heating_max
    for: "00:05:00"
  - platform: state
    entity_id:
      - climate.toilet
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.toilet
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.toilet
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.toilet
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: schedule.toilet_thermostat_schedule
            state: "off"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {{ states('sensor.heating_min')| float(0) }}
            target:
              entity_id: climate.toilet
      - conditions:
          - condition: state
            entity_id: schedule.toilet_thermostat_schedule
            state: "on"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {{ states('sensor.heating_max')| float(0) }}
            target:
              entity_id: climate.toilet