id: 'climate_control_auto_off'
alias: Climate Control Auto Off
initial_state: true
trigger:
  platform: numeric_state
  entity_id: sensor.outdoor_module_temperature
  above: 14
  for: "00:30:00"
condition: []
action:
  - service: switch.turn_off
    data:
      entity_id: switch.heating_control_switch
mode: single