id: 'climate_control_auto_on'
alias: Climate Control Auto On
initial_state: true
trigger:
  platform: numeric_state
  entity_id: sensor.outdoor_module_temperature
  below: 13
  for: "00:30:00"
condition:
- condition: or
  conditions:
  - condition: state
    entity_id: sensor.season
    state: spring
  - condition: state
    entity_id: sensor.season
    state: autumn
  - condition: state
    entity_id: sensor.season
    state: winter
action:
  - service: switch.turn_on
    data:
      entity_id: switch.heating_control_switch
mode: single