id: "57fa7e86-c3b4-4cf2-bb41-23f1f55dcd43"
alias: "Climate Control Door"
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: 
      - binary_sensor.front_door
      - binary_sensor.back_door
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
  - condition: numeric_state
    entity_id: sensor.outdoor_module_temperature
    below: 13
action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.front_door
          state: 'on'
        - condition: state
          entity_id: binary_sensor.back_door
          state: 'on'
      sequence:
      - service: climate.turn_off
        data: {}
        target:
          entity_id: 
            - climate.dining_room
            - climate.hallway_2
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.front_door
          state: 'off'
        - condition: state
          entity_id: binary_sensor.back_door
          state: 'off'
      sequence:
      - service: climate.turn_on
        data: {}
        target:
          entity_id: 
            - climate.dining_room
            - climate.hallway_2