id: '57fa7e86-c3b4-4cf2-bb41-23f1f55dcd43'
alias: Climate Control Door
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: 
      - binary_sensor.fibaro_door_window_sensor_2_window_door_is_open_2
      - binary_sensor.fibaro_door_window_sensor_2_window_door_is_open
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
  - condition: state
    entity_id: climate.bedroom_1
    state: "heat"
action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.fibaro_door_window_sensor_2_window_door_is_open_2
          state: 'on'
        - condition: state
          entity_id: binary_sensor.fibaro_door_window_sensor_2_window_door_is_open
          state: 'on'
      sequence:
      - service: climate.turn_off
        data: {}
        target:
          entity_id: 
            - climate.dining_room
            - climate.hallway_2
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.fibaro_door_window_sensor_2_window_door_is_open_2
          state: 'off'
        - condition: state
          entity_id: binary_sensor.fibaro_door_window_sensor_2_window_door_is_open
          state: 'off'
      sequence:
      - service: climate.turn_on
        data: {}
        target:
          entity_id: 
            - climate.dining_room
            - climate.hallway_2