id: "926f12bb-742d-4817-8bf4-fcee5f60e0a8"
alias: "Climate Control Heating"
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type:
      - automation_reloaded
  - platform: state
    entity_id: sensor.outdoor_module_temperature
    for:
      hours: 0
      minutes: 10
      seconds: 0
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.outdoor_module_temperature
            above: 14
        sequence:
          - service: climate.turn_off
            data: {}
            target:
              entity_id:
                - climate.bedroom_1
                - climate.bathroom
                - climate.bedroom_2
                - climate.living_room
                - climate.bedroom_3
                - climate.toilet
                - climate.hallway_2
                - climate.dining_room
      - conditions:
          - condition: numeric_state
            entity_id: sensor.outdoor_module_temperature
            below: 14
        sequence:
          - service: climate.turn_on
            data: {}
            target:
              entity_id:
                - climate.bedroom_1
                - climate.bathroom
                - climate.bedroom_2
                - climate.living_room
                - climate.bedroom_3
                - climate.toilet
                - climate.hallway_2
                - climate.dining_room