id: "a7c4a997-5c9b-40d5-b37c-4dbba0625890"
alias: "Climate Control Window"
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.dining_room_window
      - binary_sensor.kitchen_window
      - binary_sensor.living_room_left_window
      - binary_sensor.living_room_right_window
      - binary_sensor.toilet_window
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
  - condition: numeric_state
    entity_id: sensor.outdoor_module_temperature
    below: 14
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.dining_room_window
                state: "on"
              - condition: state
                entity_id: binary_sensor.kitchen_window
                state: "on"
        sequence:
          - service: climate.turn_off
            data: {}
            target:
              entity_id: 
                - climate.dining_room
                - climate.hallway_2
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.dining_room_window
                state: "off"
              - condition: state
                entity_id: binary_sensor.kitchen_window
                state: "off"
        sequence:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: 
                - climate.dining_room
                - climate.hallway_2
      - conditions:
          - condition: state
            entity_id: binary_sensor.toilet_window
            state: "on"
        sequence:
          - service: climate.turn_off
            data: {}
            target:
              entity_id: 
                - climate.toilet
                - climate.hallway_2
      - conditions:
          - condition: state
            entity_id: binary_sensor.toilet_window
            state: "off"
        sequence:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: 
                - climate.toilet
                - climate.hallway_2
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.living_room_left_window
                state: "on"
              - condition: state
                entity_id: binary_sensor.living_room_right_window
                state: "on"
        sequence:
          - service: climate.turn_off
            data: {}
            target:
              entity_id: 
                - climate.livingroom_radiator
                - climate.hallway_2
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.living_room_left_window
                state: "off"
              - condition: state
                entity_id: binary_sensor.living_room_right_window
                state: "off"
        sequence:
          - service: climate.turn_on
            data: {}
            target:
              entity_id: 
                - climate.livingroom_radiator
                - climate.hallway_2