# Base Configuration:
homeassistant:
  name: !secret base_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  currency: GBP
  time_zone: Europe/London
  external_url: !secret remote_base
  internal_url: !secret local_base
  packages: !include_dir_named integrations
  customize: !include_dir_merge_named customizations/entities/
  country: GB
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info
  
api:

# discovery:

ffmpeg:

downloader:
  download_dir: downloads

python_script:

wake_on_lan:

media_source:

cloud:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

lovelace: !include lovelace.yaml

conversation:

# file location: config/www/calendar.ics
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/bin.ics"
      customize:
        - type: Brown Bin
          alias: Garden Waste
