id: '87f07734-91f1-4d1f-8880-60f089344bbe'
alias: Lights Bedroom 3 Light
description: ''
trigger:
  - platform: state
    entity_id: light.bedroom_3_light
    to: "on"
  - platform: time
    at: '22:00:10'
  - platform: state
    entity_id: input_boolean.person4_home
condition:
  - condition: state
    entity_id: light.bedroom_3_light
    state: "on"
action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person4_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.home_night
          state: 'on'
#        - condition: state
#          entity_id: light.bedroom_3_light
#          state: "on"
      sequence:
      - service: light.turn_on
        data_template:
          brightness_pct: 100
          color_name: >
            {% if is_state('sensor.holiday_name', 'Halloween') %}
              orange
            {% else %}
              green
            {% endif %}
        target:
          entity_id: light.bedroom_3_light
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person4_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.home_night
          state: 'on'
#        - condition: state
#          entity_id: light.bedroom_3_light
#          state: "on"
        - condition: time
          after: '22:00:00'
      sequence:
      - service: light.turn_on
        data_template:
          brightness_pct: 50
          color_name: >
            {% if is_state('sensor.holiday_name', 'Halloween') %}
              orange
            {% else %}
              green
            {% endif %}
        target:
          entity_id: light.bedroom_3_light
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person4_home
          state: "off"
        - condition: state
          entity_id: input_boolean.home_night
          state: "on"
#        - condition: state
#          entity_id: light.bedroom_3_light
#          state: "on"
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 100
          color_temp: 111
        target:
          entity_id: light.bedroom_3_light
    - conditions:
      - condition: state
        entity_id: input_boolean.person4_home
        state: 'off'
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: 
            - light.bedroom_3_light
            - light.bedroom_3_led
            - light.bedroom_3_lamp
    default: []
mode: single