id: '68206d72-011f-4cd1-9244-31f49e7c6ba5'
alias: Light Bedroom 3 Light Off
initial_state: true
description: ""
mode: single
trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == states('sensor.light_off') }}"
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
        - light.bedroom_3_lamp
        - light.bedroom_3_led
        - light.bedroom_3_light