id: '68206d72-011f-4cd1-9244-31f49e7c6ba5'
alias: Light Bedroom 3 Light Off
initial_state: true
description: ""
mode: single
trigger:
  - platform: template
    value_template: >-
      {{ states('sensor.time') == (
      states.input_datetime.bedroom_3_light.attributes.timestamp | int - 300 ) |
      timestamp_custom('%H:%M', False) }}
  - platform: state
    entity_id:
      - input_boolean.person4_home
    to: "off"
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.person4_home
            state: "on"
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id:
                - light.bedroom_3_led
                - light.bedroom_3_light
          - service: light.turn_off
            data:
              transition: 300
            target:
              entity_id: light.bedroom_3_lamp
      - conditions:
          - condition: state
            entity_id: input_boolean.person4_home
            state: "off"
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id:
                - light.bedroom_3_lamp
                - light.bedroom_3_led
                - light.bedroom_3_light