id: 'a90da5eb-fb21-475a-bafb-4557b1769d58'
alias: Lights Bedroom 3 TV Led Strip
initial_state: true
description: ''
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.home_night
    to: "on"
condition:
  - condition: state
    entity_id: media_player.lg_webos_tv_uk6300plb
    state: "on"
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.bedroom_3_tv_led