id: 'b141bcea-ac32-4bc1-b403-00ef47cd1dc4'
alias: Switch Bedroom 2 Plug
initial_state: true
trigger:
  - platform: state
    entity_id:
    - input_boolean.person5_home
condition: []
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.person5_home
        state: 'off'
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: 
            - switch.bedroom_2_tv_plug
            - switch.sonoff_1000f535fe_1
    - conditions:
      - condition: state
        entity_id: input_boolean.person5_home
        state: 'on'
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: 
            - switch.bedroom_2_tv_plug
mode: single