id: "5e08e44b-328e-40d7-8578-2f2345cd893c"
alias: "USB Bedroom 2"
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: sensor.amelia_s_phone_battery_level
  - platform: template
    value_template: 
      "{% set alarm_time = states('sensor.bedroom_2_echo_show_next_alarm') | as_datetime %}
      {% set minutes_before = 60 %} 
      {% if alarm_time != None %}
      {{ now() >= alarm_time - timedelta(minutes = minutes_before) }}
      {% else %} 
        False 
      {% endif %}"
condition:
  - condition: state
    entity_id: input_boolean.person5_home
    state: 'on'
action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.amelia_s_phone_battery_level
        above:  99
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.sonoff_1000f535fe_1
    - conditions:
      - condition: numeric_state
        entity_id: sensor.amelia_s_phone_battery_level
        below: 26
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.sonoff_1000f535fe_1
    - conditions:
      - condition: template
        value_template:
          "{% set alarm_time = states('sensor.bedroom_2_echo_show_next_alarm') | as_datetime %}
          {% set minutes_before = 60 %} 
          {% if alarm_time != None %}
          {{ now() >= alarm_time - timedelta(minutes = minutes_before) }}
          {% else %} 
            False 
          {% endif %}"
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.sonoff_1000f535fe_1
