id: '2a56f4e3-13e3-4b81-ac1e-3bb880c8da9e'
alias: Lights Living Room Lamp On
initial_state: true
description: ''
trigger:
  - platform: state
    entity_id: input_boolean.home_night
    to: "on"
condition: []
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.livingroom_lamp
mode: single