id: '0f969975-1ac7-4476-99b7-aa0cf31ebb2d'
alias: Lights Living Room Lamp Theme
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: calendar.holidays
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: calendar.holidays
                state: "on"
              - condition: state
                entity_id: calendar.holidays
                attribute: message
                state: Valentine's Day
        sequence:
          - service: lifx.set_state
            data:
              color_name: deeppink
            target:
              entity_id: light.livingroom_lamp
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: calendar.holidays
                state: "on"
              - condition: state
                entity_id: calendar.holidays
                attribute: message
                state: St Patrick's Day
        sequence:
          - service: lifx.set_state
            data:
              color_name: darkgreen
            target:
              entity_id: light.livingroom_lamp
      - conditions:
          - condition: state
            entity_id: calendar.holidays
            state: "off"
        sequence:
          - service: lifx.set_state
            data:
              kelvin: 9000
            target:
              entity_id: light.livingroom_lamp