id: '42f6a612-38ba-4f00-9992-0e1b2c0aaa5e'
alias: Climate Bedroom 2 Fan
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: sensor.bedroom_2_average_temperature
  - platform: state
    entity_id: fan.sonoff_1000cc26b0
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: sensor.season
                    state: winter
              - condition: state
                entity_id: fan.sonoff_1000cc26b0
                state: "on"
        sequence:
          - service: fan.set_percentage
            data_template:
              percentage: >
                {% if states('sensor.bedroom_2_average_temperature') | float <
                20 %}
                  33
                {% elif states('sensor.bedroom_2_average_temperature') | float <
                25 %}
                  66
                {% elif states('sensor.bedroom_2_average_temperature') | float <
                35 %}
                  100
                {% endif %}
            target:
              entity_id: fan.sonoff_1000cc26b0
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.season
                state: winter
              - condition: state
                entity_id: fan.sonoff_1000cc26b0
                state: "on"
        sequence:
          - service: fan.set_percentage
            data:
              percentage: 33
            target:
              entity_id: fan.sonoff_1000cc26b0
          - service: climate.set_preset_mode
            data:
              preset_mode: sleep
            target:
              entity_id:
                - climate.bedroom_2
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: fan.sonoff_1000cc26b0
                state: "off"
              - condition: state
                entity_id: input_boolean.home_sleep
                state: "off"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: none
            target:
              entity_id:
                - climate.bedroom_2
