id: 'f4e73590-9189-43bb-a787-9dd4bff1d0c0'
alias: Climate Bedroom 2 Radiator Schedule
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type:
      - automation_reloaded
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id: 
      - climate.bedroom_2
    to: "heat"
  - platform: state
    entity_id:
      - input_number.heating_minimum
      - input_number.heating_maximum
  - platform: state
    entity_id:
      - climate.bedroom_2
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.bedroom_2
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.bedroom_2
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.bedroom_2
action:
  - choose:
      - conditions:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ now().hour in [7, 17, 18, 19, 20, 21 ] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {{ states('input_number.heating_minimum')| float(0)-2 }}
            target:
              entity_id: climate.bedroom_2
      - conditions:
          - condition: template
            value_template: "{{ now().hour in [7, 17, 18, 19, 20, 21 ] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {{ states('input_number.heating_maximum')| float(0)-2 }}
            target:
              entity_id: climate.bedroom_2