# fan.livingroom_tower_fan
- platform: template
  fans:
    living_room_fan:
      friendly_name: 'Livingroom Fan'
      unique_id: 'c2ee140f-a74e-4a70-b61c-3f920c4cae09'
      value_template: "{{ states('fan.livingroom_tower_fan') }}"
      turn_on:
        - service: fan.turn_on
          target:
            entity_id: fan.livingroom_tower_fan
      turn_off:
        - service: fan.turn_off
          target:
            entity_id: fan.livingroom_tower_fan
      percentage_template: >
        {{ state_attr('fan.livingroom_tower_fan', 'percentage') }}
      oscillating_template: > 
        {{ state_attr('fan.livingroom_tower_fan', 'oscillating') }}
      speed_count: 9
      set_percentage:
        - service: fan.set_percentage
          target:
            entity_id: fan.livingroom_tower_fan
          data:
            percentage: "{{ percentage }}"
      preset_modes:
        - "Speed 1"
        - "Speed 2"
        - "Speed 3"
        - "Speed 4"
        - "Speed 5"
        - "Speed 6"
        - "Speed 7"
        - "Speed 8"      
      preset_mode_template: >
        {% if is_state('fan.livingroom_tower_fan', 'on') %}
          {% if state_attr('fan.livingroom_tower_fan', 'percentage') == 11  %}
            Speed 1
          {% elif state_attr('fan.livingroom_tower_fan', 'percentage') == 22 %}
            Speed 2
          {% elif state_attr('fan.livingroom_tower_fan', 'percentage') == 33 %}
            Speed 3
          {% elif state_attr('fan.livingroom_tower_fan', 'percentage') == 44 %}
            Speed 4
          {% elif state_attr('fan.livingroom_tower_fan', 'percentage') == 55 %}
            Speed 5
          {% elif state_attr('fan.livingroom_tower_fan', 'percentage') == 66 %}
            Speed 6
          {% elif state_attr('fan.livingroom_tower_fan', 'percentage') == 77 %}
            Speed 7
          {% elif state_attr('fan.livingroom_tower_fan', 'percentage') == 88 %}
            Speed 8
          {% else %}
            low
          {% endif %}
        {% else %}
          off
        {% endif %}
      set_preset_mode:
        - service: fan.set_percentage
          target:
            entity_id: fan.livingroom_tower_fan
          data:
            percentage: >-
              {% if preset_mode == 'Speed 1' %}
                11
              {% elif preset_mode == 'Speed 2' %}
                22
              {% elif preset_mode == 'Speed 3' %}
                33
              {% elif preset_mode == 'Speed 4' %}
                44
              {% elif preset_mode == 'Speed 5' %}
                55
              {% elif preset_mode == 'Speed 6' %}
                66
              {% elif preset_mode == 'Speed 7' %}
                77
              {% elif preset_mode == 'Speed 8' %}
                88
              {% else %}
                0
              {% endif %}
      set_oscillating:
        - service: fan.oscillate
          target:
            entity_id: fan.livingroom_tower_fan
          data_template:
            oscillating: >-
              {% if state_attr('fan.livingroom_tower_fan', 'oscillating') == true  %}
                false
              {% elif state_attr('fan.livingroom_tower_fan', 'oscillating') == false  %}
                true
              {% endif %}