id: '86a16ba7-f9cc-4a82-bfc3-876f09c37dbc'
alias: Light Bedroom 1 Brightness
initial_state: true
description: ""
mode: single
trigger:
  - platform: time
    at: "23:01:00"
  - platform: time
    at: "06:01:00"
condition: []
action:
  - service: lifx.set_state
    data_template:
      color_temp: >
        {% if now().hour in [23, 0, 1, 2, 3, 4, 5] %} 
          370
        {% else %}
          153
        {% endif %}
      brightness_pct: >
        {% if now().hour in [23, 0, 1, 2, 3, 4, 5] %} 
          50
        {% else %}
          100
        {% endif %}
    target:
      entity_id:
        - light.bedroom_1_lamp_1
        - light.bedroom_1_lamp_2
  - service: lifx.set_state
    data_template:
      color_temp: >
        {% if now().hour in [23, 0, 1, 2, 3, 4, 5] %} 
          454
        {% else %}
          153
        {% endif %}   
      brightness_pct: >
        {% if now().hour in [23, 0, 1, 2, 3, 4, 5] %} 
          50
        {% else %}
          100
        {% endif %}
    target:
      entity_id:
        - light.bedroom_1_light