id: '86a16ba7-f9cc-4a82-bfc3-876f09c37dbc'
alias: Light Bedroom 1 Brightness
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.lights_dim
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.lights_dim
            state: "on"
        sequence:
          - service: lifx.set_state
            data_template:
              color_temp: 370
              brightness_pct: 50
            target:
              entity_id:
                - light.bedroom_1_lamp_1
                - light.bedroom_1_lamp_2
          - service: lifx.set_state
            data_template:
              color_temp: 454
              brightness_pct: 50
            target:
              entity_id:
                - light.bedroom_1_light
      - conditions:
          - condition: state
            entity_id: binary_sensor.lights_dim
            state: "off"
        sequence:
          - service: lifx.set_state
            data_template:
              color_temp: 153
              brightness_pct: 100
            target:
              entity_id:
                - light.bedroom_1_lamp_1
                - light.bedroom_1_lamp_2
          - service: lifx.set_state
            data_template:
              color_temp: 153  
              brightness_pct: 100
            target:
              entity_id:
                - light.bedroom_1_light