id: '6e22971f-cfd3-494c-a771-dbf07b183ea4'
alias: Lights Bedroom 1 Lamp
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: 
      - light.bedroom_1_lamp_1
      - light.bedroom_1_lamp_2
      - light.bedroom_1_lamps
    to: "on"
condition: []
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.home_alarm_triggered
        state: "off"
      sequence:
      - service: lifx.set_state
        data_template:
          color_temp: >
            {% if now().hour in [23, 0, 1, 2, 3, 4, 5, 6] %} 
              370
            {% else %}
              153
            {% endif %}
          brightness_pct: >
            {% if now().hour in [23, 0, 1, 2, 3, 4, 5, 6] %} 
              50
            {% else %}
              100
            {% endif %}
          transition: 5
        target:
          entity_id:
            - light.bedroom_1_lamp_1
            - light.bedroom_1_lamp_2
    - conditions:
      - condition: state
        entity_id: input_boolean.home_alarm_triggered
        state: "on"
      sequence:
      - service: lifx.set_state
        data:
          color_temp: 370
          brightness_pct: 100
        target:
          entity_id:
            - light.bedroom_1_lamp_1
            - light.bedroom_1_lamp_2