id: '802384af-4478-490c-9d29-2fa8eb28dd3f'
alias: Climate Bedroom 3 Away
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.person4_home
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.person4_home
            state: "on"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: none
            target:
              entity_id: climate.bedroom_3
      - conditions:
          - condition: state
            entity_id: input_boolean.person4_home
            state: "off"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: away
            target:
              entity_id: climate.bedroom_3