id: '626cba67-ad2c-4bc2-b7b6-844fb9128dea'
alias: Climate Bedroom 3 Fan
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: sensor.bedroom_3_average_temperature
  - platform: state
    entity_id: fan.sonoff_1000cc1c61
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: sensor.season
                    state: winter
              - condition: state
                entity_id: fan.sonoff_1000cc1c61
                state: "on"
        sequence:
          - service: fan.set_percentage
            data_template:
              percentage: >
                {% if states('sensor.bedroom_3_average_temperature') | float <
                20 %}
                  33
                {% elif states('sensor.bedroom_3_average_temperature') | float <
                25 %}
                  66
                {% elif states('sensor.bedroom_3_average_temperature') | float <
                35 %}
                  100
                {% endif %}
            target:
              entity_id: fan.sonoff_1000cc1c61
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.season
                state: winter
              - condition: state
                entity_id: fan.sonoff_1000cc1c61
                state: "on"
        sequence:
          - service: fan.set_percentage
            data:
              percentage: 33
            target:
              entity_id: fan.sonoff_1000cc1c61
          - service: climate.set_preset_mode
            data:
              preset_mode: sleep
            target:
              entity_id:
                - climate.bedroom_3
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: fan.sonoff_1000cc1c61
                state: "off"
              - condition: state
                entity_id: input_boolean.home_sleep
                state: "off"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: none
            target:
              entity_id:
                - climate.bedroom_3
