id: '626cba67-ad2c-4bc2-b7b6-844fb9128dea'
alias: Climate Bedroom 3 Fan
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - fan.sonoff_1000cc1c61
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 10
  - platform: state
    entity_id: sensor.tado_smart_radiator_thermostat_va0943328000_current_temperature
  - platform: state
    entity_id: input_boolean.person4_home
condition:
  - condition: state
    entity_id: fan.sonoff_1000cc1c61
    state: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 10
action:
  - choose:
      - conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.season
                state: winter
        sequence:
          - service: fan.set_percentage
            data_template:
              percentage: >
                {% if states('sensor.tado_smart_radiator_thermostat_va0943328000_current_temperature') | float < 20 %}
                  33
                {% elif states('sensor.tado_smart_radiator_thermostat_va0943328000_current_temperature') | float < 25 %}
                  66
                {% elif states('sensor.tado_smart_radiator_thermostat_va0943328000_current_temperature') | float < 35 %}
                  100
                {% endif %}
            target:
              entity_id: fan.sonoff_1000cc1c61
      - conditions:
          - condition: state
            entity_id: sensor.season
            state: winter
        sequence:
          - service: fan.set_percentage
            data:
              percentage: 33
            target:
              entity_id: fan.sonoff_1000cc1c61
      - conditions:
        - condition: state
          entity_id: input_boolean.person4_home
          state: "off"
        sequence:
        - service: fan.turn_off
          target:
            entity_id: fan.sonoff_1000cc1c61