id: '3245d329-83e4-437d-b852-8babf6462009'
alias: Climate Bedroom 3 Fan Off
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - fan.sonoff_1000cc1c61
    to: "off"
condition:
  - condition: state
    entity_id: input_boolean.home_sleep
    state: "off"
action:
  - service: climate.set_preset_mode
    data:
      preset_mode: none
    target:
      entity_id: climate.bedroom_3