id: 'a15c3545-2297-474e-9a29-cfcaf800565a'
alias: Climate Bedroom 3 Radiator Schedule
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type:
      - automation_reloaded
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id: 
      - climate.bedroom_3
    to: "heat"
  - platform: state
    entity_id:
      - input_number.heating_minimum
      - input_number.heating_maximum
  - platform: state
    entity_id:
      - climate.bedroom_3
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.bedroom_3
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.bedroom_3
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.bedroom_3
action:
  - choose:
      - conditions:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ now().hour in [7, 17, 18, 19, 20, 21 ] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {{ states('input_number.heating_minimum')| float(0)-2 }}
            target:
              entity_id: climate.bedroom_3
      - conditions:
          - condition: template
            value_template: "{{ now().hour in [7, 17, 18, 19, 20, 21 ] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {{ states('input_number.heating_maximum')| float(0)-2 }}
            target:
              entity_id: climate.bedroom_3