id: be7ec595-c382-4b59-a769-1183b79d8076
alias: Climate Bedroom 3 Radiator Warning
initial_state: true
trigger:
  - entity_id: binary_sensor.climate_bedroom_3_heating_warning
    for: 01:00:00
    platform: state
    to: 'on'
condition: []
action:
  - service: script.notify_message_engine
    data:
      who: home_app
      title: "Heating Warning"
      message: "Warning Bedroom 3 Radiator has been heating for 60 minutes"
  - service: switch.turn_off
    data:
      entity_id: switch.heating_bedroom_3_control_switch