################################################################################
#
# When person 1 returns home turn on boolean input
#
################################################################################

id: '3fd539b4-944f-4570-8519-4d65296e8f8e'
alias: Person 1 Returns Home
initial_state: true
trigger:
  - platform: zone
    entity_id: person.person_1
    zone: zone.home
    event: enter
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.person1_home
mode: single