id: 'd6860667-cefa-433a-8b57-126fd2ba81ee'
alias: Date/Time Bedroom 3 Light
initial_state: true
description: ""
mode: single
trigger:
  - platform: time
    at: "06:00:00"
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.home_holiday
                state: "on"
              - condition: time
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - sun
        sequence:
          - service: input_datetime.set_datetime
            data:
              time: "23:50:00"
            target:
              entity_id: input_datetime.bedroom_3_light
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.home_holiday
                state: "off"
              - condition: time
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - sun
        sequence:
          - service: input_datetime.set_datetime
            data:
              time: "22:55:00"
            target:
              entity_id: input_datetime.bedroom_3_light
      - conditions:
          - condition: time
            weekday:
              - fri
              - sat
        sequence:
          - service: input_datetime.set_datetime
            data:
              time: "23:50:00"
            target:
              entity_id: input_datetime.bedroom_3_light