id: '0bc143c8-3cfd-41a2-9772-715a9736e9d8'
alias: Date/Time Bedroom 3 TV
initial_state: true
description: ""
mode: single
trigger:
  - platform: time
    at: "06:00:00"
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.home_holiday
                state: "on"
              - condition: time
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - sun
        sequence:
          - service: input_datetime.set_datetime
            data:
              time: "23:55:00"
            target:
              entity_id: input_datetime.bedroom_3_tv
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.home_holiday
                state: "off"
              - condition: time
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - sun
        sequence:
          - service: input_datetime.set_datetime
            data:
              time: "23:00:00"
            target:
              entity_id: input_datetime.bedroom_3_tv
      - conditions:
          - condition: time
            weekday:
              - fri
              - sat
        sequence:
          - service: input_datetime.set_datetime
            data:
              time: "23:55:00"
            target:
              entity_id: input_datetime.bedroom_3_tv