id: "5db81424-4a62-40eb-b050-01d29019c7b1"
alias: "Notification HACS Update"
description: ""
initial_state: true
mode: single
trigger:
  - platform: numeric_state
    entity_id: sensor.hacs
    above: 0 
#  - platform: state
#    entity_id: sensor.hacs
condition: []
action:
  - service: script.notify_message_engine
    data:
      who: home_app
      title: Updates ({{ states('sensor.hacs') }}) pending in HACS
      message: >-
        {% for repo in state_attr('sensor.hacs', 'repositories') %}
          **{{ repo.display_name }}** _{{ repo["installed version"] }}_ -> _{{ repo["available version"] }}_
        {% endfor %}