- platform: template
  sensors:
    climate_bedroom_2_heating_warning:
      friendly_name: "Heating in Bedroom 2"
      unique_id: '419e4669-f489-4c37-a9e9-4cab7e24aacc'
      value_template: '{{ state_attr("climate.tado_smart_radiator_thermostat_va2514946816","hvac_action") == "heating" }}'    