id: 'c5231ca1-13aa-457e-b729-2c9a3826a6ee'
alias: Home Home Heating
description: ''
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id:
    - input_boolean.home_home
    to: 'on'
condition: []
action:
  - service: climate.set_preset_mode
    data:
      preset_mode: none
    target:
      entity_id:
        - climate.bathroom
        - climate.bedroom_1
        - climate.living_room
        - climate.dining_room
        - climate.toilet
        - climate.hallway_2