id: '367fa52c-be7e-4d11-96ff-6e140917d355'
alias: Home Home Switch
initial_state: true
description: ''
trigger:
#  - platform: state
#    entity_id:
#    - input_boolean.home_away
  - platform: state
    entity_id:
    - input_boolean.person1_home
    to: 'on'
  - platform: state
    entity_id:
    - input_boolean.person2_home
    to: 'on'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.person1_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.person2_home
      state: 'on'
action:
  - choose:
    - conditions:
      - condition: sun
        before: sunset
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: 
            - input_boolean.home_home
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.home_away
    - conditions:
      - condition: sun
        after: sunset
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: 
            - input_boolean.home_night
            - input_boolean.home_home
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.home_away
mode: single
