id: '10c4ed84-67ac-4234-b5ce-e82dd5fb6c09'
alias: Remotec Bedroom 3 Press Button One 1x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "ee077bf18084ecee4855b0e8bd294e8e"
      property_key: "001"
      value: "KeyPressed"
condition: []
action:
  - service: light.toggle
#    data:
#      transition: 1
    target:
      entity_id: light.bedroom_3_light
mode: single