id: '7bdd510f-540d-4ab7-83ef-9704b77d05c7'
alias: Remotec Bedroom 3 Press Button Three 1x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "ee077bf18084ecee4855b0e8bd294e8e"
      property_key: "003"
      value: "KeyPressed"
condition: []
action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.bedroom_3_tv_power
mode: single