id: "92d277f7-598d-4b94-85e0-93d713ba0bbe"
alias: "Camera Ring Doorbell Download"
description: ""
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.front_door_ding
    to: "on"
condition: []
action:
  - service: downloader.download_file
    data:
      url: "{{ state_attr('camera.front_door', 'video_url') }}"
      subdir: "{{state_attr('camera.front_door', 'friendly_name')}}"
      filename: "{{state_attr('camera.front_door', 'friendly_name')}}"