id: '11769baa-6822-426c-8b94-e087c3e26524'
alias: Home Away Heating
description: ''
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id:
    - input_boolean.home_away
    to: 'on'
condition: []
action:
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    target:
      entity_id:
        - climate.bathroom
        - climate.bedroom_1
        - climate.living_room
        - climate.dining_room
        - climate.toilet
        - climate.hallway_2