id: 'c55a7a1c-e126-4ebe-863c-de611e7e42cc'
alias: Home Away Switch
initial_state: true
description: ''
mode: single
trigger:
  - platform: state
    entity_id:
    - input_boolean.home_away
    to: 'on'
condition: []
action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: 
        - switch.livingroom_plug_socket_4
        - switch.livingroom_plug_socket_1
        - switch.dining_room_switch_2
        - switch.kitchen_plug_socket_3
        - switch.livingroom_plug_socket_4