id: '91a07baa-d06b-4657-a70a-b7bd809fb0d7'
alias: Landing Landing
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.trisensor_motion_detection_2
condition:
  - condition: state
    entity_id: input_boolean.home_night
    state: "on"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.trisensor_motion_detection_2
            state: "on"
        sequence:
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.landing_light
      - conditions:
          - condition: state
            entity_id: binary_sensor.trisensor_motion_detection_2
            state: "off"
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.landing_light
mode: restart