id: "2e7cfe8b-4ba2-4f51-8cce-f38f6311cf58"
alias: "Light Bedroom 2 Brightness"
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.lights_dim
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.lights_dim
            state: "on"
        sequence:
          - service: lifx.set_state
            data_template:
              brightness_pct: 20
            target:
              entity_id:
                - light.bedroom_2_lamp
                - light.bedroom_2_light
      - conditions:
          - condition: state
            entity_id: binary_sensor.lights_dim
            state: "off"
        sequence:
          - service: lifx.set_state
            data_template:
              brightness_pct: 100
            target:
              entity_id:
                - light.bedroom_2_lamp
                - light.bedroom_2_light