id: 'fe327f2a-17e5-4e50-a783-6040165c3a04'
alias: Light Bedroom 2 Lamp
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: light.bedroom_2_lamp
    to: "on"
  - platform: time
    at: "22:00:00"
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.person5_home
            state: "on"
        sequence:
          - service: lifx.set_state
            data_template:
              brightness_pct: >
                {% if now().hour in [22, 23, 0, 1, 2, 3, 4, 5, 6] %} 
                  20
                {% else %}
                  100
                {% endif %}
              transition: 2
            target:
              entity_id: light.bedroom_2_lamp
      - conditions:
          - condition: state
            entity_id: input_boolean.person5_home
            state: "off"
        sequence:
          - service: lifx.set_state
            data:
              brightness_pct: 100
            target:
              entity_id: light.bedroom_2_lamp