id: '94ba2b94-ca01-45f4-b7a3-4160c3cbb9cb'
alias: Light Bedroom 2 Lamp On
initial_state: true
description: ''
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.home_night
    to: "on"
condition:
  - condition: state
    entity_id: media_player.lg_webos_tv_up77006lb
    state: "on"
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.bedroom_2_lamp