id: 'fb35c4ec-7682-411d-abbe-0e2876405883'
alias: Light Bedroom 2 Light
initial_state: true
trigger:
  - platform: state
    entity_id: light.bedroom_2_light
    to: "on"
  - platform: time
    at: '22:00:10'
  - platform: state
    entity_id: input_boolean.person5_home
condition:
  - condition: state
    entity_id: light.bedroom_2_light
    state: "on"
action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person5_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.home_night
          state: 'on'
      sequence:
      - service: light.turn_on
        data_template:
          brightness: 255
          color_name: >
            {% if is_state('sensor.holiday_name', 'Halloween') %}
              orange
            {% else %}
              blue
            {% endif %}
        target:
          entity_id: light.bedroom_2_light
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person5_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.home_night
          state: 'on'
        - condition: time
          after: '22:00:00'
      sequence:
      - service: light.turn_on
        data_template:
          brightness: 51
          color_name: >
            {% if is_state('sensor.holiday_name', 'Halloween') %}
              orange
            {% else %}
              blue
            {% endif %}
        target:
          entity_id: light.bedroom_2_light
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person5_home
          state: "off"
        - condition: state
          entity_id: input_boolean.home_night
          state: "on"
      sequence:
      - service: light.turn_on
        data:
          brightness: 255
          color_temp: 111
        target:
          entity_id: light.bedroom_2_light
    - conditions:
      - condition: state
        entity_id: input_boolean.person5_home
        state: 'off'
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: 
            - light.bedroom_2_light
            - light.bedroom_2_led
            - light.bedroom_2_lamp
    default: []
mode: single