id: '4cd6040f-ce4a-4c57-bda4-b5de3f9a6d54'
alias: Light Bedroom 2 Light Off
initial_state: true
description: ""
mode: single
trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == states('sensor.light_off') }}"
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
        - light.bedroom_2_lamp
        - light.bedroom_2_led
        - light.bedroom_2_light