- platform: min_max
  name: Bathroom Average Humidity
  unique_id: 'b8041591-2a52-4cd6-95b2-9a4ba7ce11b4'
  type: mean
  entity_ids:
    - sensor.lumi_lumi_weather_humidity
    - sensor.tado_smart_radiator_thermostat_va4266461696_current_humidity