- platform: min_max
  name: Bedroom 2 Average Humidity
  unique_id: '7ec922ea-d204-4d41-aaf7-c85e719c481f'
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.tado_smart_radiator_thermostat_va2514946816_current_humidity
    - sensor.lumi_lumi_weather_humidity_6