id: '47e9074a-0dfa-4d15-b678-d5744267d7fa'
alias: Switch Playstation Off
initial_state: on
trigger:
  - platform: template
    value_template: >
      {% if is_state('input_boolean.home_holiday', 'off') %}
        {{ is_state('sensor.time', '21:30') }}
      {% else %}
        {{ is_state('sensor.time', '22:30') }}
      {% endif %}
condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
action:
  - service: switch.turn_off
    data:
      entity_id: switch.tyler_s_playstation
mode: single