id: 'dabbaeff-f913-41c4-8d47-904eda3c664c'
alias: Switch Bedroom 3 Plug
initial_state: true
trigger:
  - platform: state
    entity_id:
    - input_boolean.person4_home
condition: []
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.person4_home
        state: 'off'
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: 
            - switch.bedroom_3_ps4_plug
            - switch.bedroom_3_tv_plug
            - switch.sonoff_1000f53b8e_1
    - conditions:
      - condition: state
        entity_id: input_boolean.person4_home
        state: 'on'
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: 
            - switch.bedroom_3_ps4_plug
            - switch.bedroom_3_tv_plug
mode: single