- platform: template
  sensors:
    dining_room_window:
      friendly_name: "Dining Room Window"
      unique_id: "69f89401-c1ef-4166-82f0-f1acf8648496"
      device_class: window
      value_template: >-
        {% if is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position", "on") %}
          On
        {% elif is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position", "off") %}
          Off
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position", "on") %}
          mdi:window-open
        {% elif is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position", "off") %}
          mdi:window-closed
        {% else %}
          false
        {% endif %}