- platform: template
  sensors:
    kitchen_window:
      friendly_name: "Kitchen Window"
      unique_id: '5f7054a5-393d-44e0-9323-5323b42fe943'
      device_class: window
      value_template: >-
        {% if is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position_5", "on") %}
          On
        {% elif is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position_5", "off") %}
          Off
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position_5", "on") %}
          mdi:window-open
        {% elif is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position_5", "off") %}
          mdi:window-closed
        {% else %}
          mdi:blinds-horizontal-closed
        {% endif %}