- platform: template
  sensors:
    living_room_right_window:
      friendly_name: "Living Room Right Window"
      unique_id: '608f6898-0bfa-4d68-aaf0-1ea94456cf79'
      device_class: window
      value_template: >-
        {% if is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position_4", "on") %}
          On
        {% elif is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position_4", "off") %}
          Off
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position_4", "on") %}
          mdi:window-open
        {% elif is_state("binary_sensor.door_window_sensor_7_window_door_is_open_in_regular_position_4", "off") %}
          mdi:window-closed
        {% else %}
          mdi:blinds-horizontal-closed
        {% endif %}