################################################################################
#
# Send a notification when a device has a firmware update
#
################################################################################

id: '766b8d51-ec59-402a-9a05-8602da395d54'
alias: Notification Firmware Update
initial_state: on
trigger:
  - platform: state
    entity_id: 
      - update.bathroom_fan_switch_firmware_update
      - update.bedroom_1_light_switch_firmware_update
      - update.bedroom_2_light_switch_firmware_update
      - update.bedroom_3_light_switch_firmware_update
      - update.dining_room_switch_2_firmware_update
      - update.diningroom_light_switch_firmware_update
      - update.kitchen_light_light_switch_firmware_update
      - update.livingroom_1_light_switch_firmware_update
      - update.livingroom_2_light_switch_firmware_update
      - update.toliet_light_switch_firmware_update
      - update.tumble_dryer_switch_firmware_update
    from: 'off'
    to: 'on'
action:
  # find the name of the device with update
  - variables:
      device: "{{ trigger.to_state.attributes.friendly_name }}"
  # send out the message telling about the update
  - service: script.notify_message_engine
    data:
      who: pushover
      title: Firmware Update
      message: >-
        "{{ device }} has a firmware update"
      priority: 0
      sound: incoming