id: "766b8d51-ec59-402a-9a05-8602da395d54"
alias: "Notification Shelly Firmware Update"
description: ""
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id:
      - update.bathroom_fan_switch_firmware_update
      - update.bedroom_1_light_switch_firmware_update
      - update.bedroom_1_plug_socket_1_firmware_update
      - update.bedroom_1_plug_socket_2_firmware_update
      - update.bedroom_2_light_switch_firmware_update
      - update.bedroom_2_tv_led_firmware
      - update.bedroom_3_light_switch_firmware_update
      - update.bedroom_3_tv_led_firmware
      - update.dining_room_switch_2_firmware_update
      - update.diningroom_light_switch_firmware_update
      - update.kitchen_light_switch_firmware_update
      - update.kitchen_plug_socket_3_firmware_update
      - update.livingroom_plug_socket_1_firmware_update
      - update.livingroom_plug_socket_4_firmware_update
      - update.toilet_light_switch_firmware_update
      - update.tumble_dryer_switch_firmware_update
    to: 'on'
action:
  - variables:
      device: "{{ trigger.to_state.attributes.friendly_name }}"
  - service: script.notify_message_engine
    data:
      who: home_app
      title: "Shelly update"
      message: "Shelly {{ device }} firmware update is available."