id: '5d1eba9f-fe47-495e-a0d7-3dc42f8d058f'
alias: Notification ZWave Firmware Update
description: update
trigger:
  - platform: state
    entity_id:
      - update.window_blind_controller_firmware
    to: 'on'
condition: []
action:
  - variables:
      device: "{{ trigger.to_state.attributes.friendly_name }}"
  - service: script.notify_message_engine
    data:
      who: pushover
      title: "ZWave Firmware Update"
      message: "Home Assistant {{ device }} firmware update is available."
      priority: 0
      sound: incoming
mode: single