id: "e7cf2b0b-71c5-47ce-857b-f297c42a6421"
alias: "People Person 4 Heating"
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.person4_home
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.person4_home
            state: "on"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: none
            target:
              entity_id: climate.bedroom_3
      - conditions:
          - condition: state
            entity_id: input_boolean.person4_home
            state: "off"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: away
            target:
              entity_id: climate.bedroom_3