id: "4d2bd6ce-5f9b-49a9-b039-2a9baae00886"
alias: "People Person 4 Switch"
initial_state: true
description: ''
mode: single
trigger:
  - platform: state
    entity_id: input_boolean.person4_home
condition: []
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.person4_home
        state: 'off'
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: 
            - switch.bedroom_3_ps4_plug
            - switch.bedroom_3_tv_plug
            - switch.sonoff_1000f53b8e_1
    - conditions:
      - condition: state
        entity_id: input_boolean.person4_home
        state: 'on'
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: 
            - switch.bedroom_3_ps4_plug
            - switch.bedroom_3_tv_plug