id: "d6b87309-0588-4a74-90bc-3c20cac97e56"
alias: "Notification Zone 1"
description: ""
initial_state: true
mode: single
trigger:
  - platform: zone
    entity_id:
      - person.person_1
      - person.person_2
      - person.person_4
      - person.person_5
    zone: zone.home
    event: enter
  - platform: zone
    entity_id:
      - person.person_1
      - person.person_2
      - person.person_4
      - person.person_5
    zone: zone.home
    event: leave
condition: []
action:
  - variables:
      event: "{{'has left' if trigger.event == 'leave' else 'arrived at' }}"
      person: "{{ trigger.to_state.attributes.friendly_name }}"
      zone: "{{ trigger.zone.attributes.friendly_name }}"
  - service: script.notify_message_engine
    data:
      who: home_app
      title: "Tracker"
      message: "{{ person }} {{ event }} {{ zone }}"