id: '142dceeb-5690-42db-a9ee-bd6c0bc0016f'
alias: Media Bedroom 1 TV
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - media_player.lg_webos_tv_um7100plb
    from: "off"
condition:
  - condition: state
    entity_id: input_boolean.home_sleep
    state: "on"
action:
  - service: media_player.select_source
    data:
      source: "Kodi"
    target:
      entity_id: media_player.lg_webos_tv_um7100plb