id: 'db295ec5-14a9-4221-b9f9-96fe24416484'
alias: Media Bedroom 2 TV Auto Off
initial_state: on
description: ""
mode: single
trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == states('sensor.tv_off') }}"
condition: []
action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.lg_webos_tv_up77006lb