id: '32f47125-104d-452c-8ee4-381fe16f8d8b'
alias: Cover Livingroom Alarm Open
description: ""
initial_state: true
mode: single
trigger:
  - platform: time
    at: input_datetime.bedroom_1_alarm_clock
  - platform: template
    value_template: 
      "{% set alarm_time = states('sensor.bedroom_1_echo_show_next_alarm') | as_datetime %}
      {% set minutes_before = 1 %} 
      {% if alarm_time != None %}
      {{ now() >= alarm_time - timedelta(minutes = minutes_before) }}
      {% else %} 
        False 
      {% endif %}"
condition:
  - condition: state
    entity_id: input_boolean.alarm_clock_bedroom_1
    state: "on"
action:
  - delay: 00:20:00
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.living_room_blind