################################################################################
#
# date/time sensor https://www.home-assistant.io/integrations/time_date/
#
################################################################################

- platform: template
  sensors:
    sensors_house_average_temperature:
      friendly_name: 'House Average Temperature'
      unit_of_measurement: "C"
      unique_id: 1f217bba-4128-4dbc-b150-531288510551
      value_template: >
        {% set livingroom_room_radiator = state_attr('climate.tado_smart_radiator_thermostat_va0114429440', 'temperature') | float(0) %}
        {% set toilet_radiator = state_attr('climate.tado_smart_radiator_thermostat_va1993674240', 'temperature') | float(0) %}
        {% set bedroom1_radiator = state_attr('climate.tado_smart_radiator_thermostat_va1775569408', 'temperature') | float(0) %}
        {% set bedroom2_radiator = state_attr('climate.tado_smart_radiator_thermostat_va2514946816', 'temperature') | float(0) %}
        {% set bedroom3_radiator = state_attr('climate.tado_smart_radiator_thermostat_va0943328000', 'temperature') | float(0) %}
        {% set kitchen = states('sensor.sensors_kitchen_average_temperature' ) | float(0) %}
        {% set hallway = states('sensor.sensors_hall_landing_average_temperature' ) | float(0) %}
        {% set bathroom = states('sensor.sensors_bathroom_average_temperature' ) | float(0) %}
        {{ ((livingroom_room_radiator + toilet_radiator + bedroom1_radiator + bedroom2_radiator + bedroom3_radiator + kitchen + hallway + bathroom ) / 8) | round(1, default=0) }}