- platform: template
  sensors:
    front_door:
      friendly_name: "Front Door"
      unique_id: "8b8c143a-a7c2-4694-9f53-3561614105ee"
      device_class: door
      value_template: >-
        {% if is_state("binary_sensor.front_door_window_door_is_open_2", "on") %}
          On
        {% elif is_state("binary_sensor.front_door_window_door_is_open_2", "off") %}
          Off
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.front_door_window_door_is_open_2", "on") %}
          mdi:door-open
        {% elif is_state("binary_sensor.front_door_window_door_is_open_2", "off") %}
          mdi:door-closed
        {% else %}
          false
        {% endif %}