- platform: template
  switches:
    heating_bathroom_tado:
      friendly_name: 'Heating Bathroom'
      unique_id: '0cdae812-5d74-438f-a691-34b956bf93bd'
      turn_on:
        - service: climate.set_temperature
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va4266461696
            temperature: 25
      turn_off:
        - service: climate.set_temperature
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va4266461696
            temperature: 5