- platform: template
  switches:
    heating_bathroom_control_switch:
      friendly_name: 'Heating Bathroom'
      unique_id: '7881d63b-5e0d-47c6-be83-96f3ba2fca58'
      value_template: > 
        {{ is_state('climate.tado_smart_radiator_thermostat_va4266461696', 'heat')}}
      turn_on:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va4266461696
            hvac_mode: heat
      turn_off:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va4266461696
            hvac_mode: 'off'
      icon_template: >-
        {% if is_state('climate.tado_smart_radiator_thermostat_va4266461696', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}