- platform: template
  switches:
    heating_bedroom_2_control_switch:
      friendly_name: 'Heating Bedroom 2'
      unique_id: 3a1f3467-a703-4814-9196-fd1e42ae58f6
      value_template: > 
        {{ is_state('climate.tado_smart_radiator_thermostat_va2514946816', 'heat')}}
      turn_on:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va2514946816
            hvac_mode: heat
      turn_off:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va2514946816
            hvac_mode: 'off'
      icon_template: >-
        {% if is_state('climate.tado_smart_radiator_thermostat_va2514946816', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}