- platform: template
  switches:
    heating_bedroom_1_control_switch:
      friendly_name: 'Heating Bedroom 1'
      unique_id: 73b66dc9-7ffd-4460-80f1-fbca706078ff
      value_template: > 
        {{ is_state('climate.tado_smart_radiator_thermostat_va1775569408', 'heat')}}
      turn_on:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va1775569408
            hvac_mode: heat
      turn_off:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va1775569408
            hvac_mode: 'off'
      icon_template: >-
        {% if is_state('climate.tado_smart_radiator_thermostat_va1775569408', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}