- platform: template
  switches:
    heating_bedroom_3_control_switch:
      friendly_name: 'Heating Bedroom 3'
      unique_id: 89554537-b179-4ab5-93c0-52d53c890e8c
      value_template: > 
        {{ is_state('climate.tado_smart_radiator_thermostat_va0943328000', 'heat')}}
      turn_on:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va0943328000
            hvac_mode: heat
      turn_off:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va0943328000
            hvac_mode: 'off'
      icon_template: >-
        {% if is_state('climate.tado_smart_radiator_thermostat_va0943328000', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}