- platform: template
  switches:
    heating_control_switch:
      friendly_name: 'Heating Control'
      unique_id: 'e213fe1a-67e9-4929-b183-6be2f8cccfb0'
      value_template: > 
        {{ is_state("switch.heating_bedroom_1_control_switch", 'on')
            or is_state("switch.heating_bedroom_2_control_switch", "on")
            or is_state("switch.heating_bedroom_3_control_switch", "on")
            or is_state("switch.heating_bathroom_control_switch", "on")
            or is_state("switch.heating_dining_room_control_switch", "on")
            or is_state("switch.heating_livingroom_control_switch", "on")
            or is_state("switch.heating_hallway_control_switch", "on")
            or is_state("switch.heating_toilet_control_switch", "on")}}
      turn_on:
        - service: switch.turn_on
          data:
            entity_id:
              - switch.heating_bedroom_1_control_switch
              - switch.heating_bedroom_2_control_switch
              - switch.heating_bedroom_3_control_switch
              - switch.heating_bathroom_control_switch
              - switch.heating_dining_room_control_switch
              - switch.heating_livingroom_control_switch
              - switch.heating_hallway_control_switch
              - switch.heating_toilet_control_switch
      turn_off:
        - service: switch.turn_off
          data:
            entity_id:
              - switch.heating_bedroom_1_control_switch
              - switch.heating_bedroom_2_control_switch
              - switch.heating_bedroom_3_control_switch
              - switch.heating_bathroom_control_switch
              - switch.heating_dining_room_control_switch
              - switch.heating_livingroom_control_switch
              - switch.heating_hallway_control_switch
              - switch.heating_toilet_control_switch
      icon_template: >-
        {% if is_state('switch.heating_control_switch', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}