- platform: template
  switches:
    heating_dining_room_tado:
      friendly_name: "Heating Dining Room"
      unique_id: "c8ecbedb-6d26-44d1-af6d-ea187dad3432"
      turn_on:
        - service: climate.set_temperature
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va0096931328
            temperature: 25
      turn_off:
        - service: climate.set_temperature
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va0096931328
            temperature: 5