- platform: template
  switches:
    heating_dining_room_control_switch:
      friendly_name: 'Heating Dining Room'
      unique_id: 353a1179-c5e9-463a-be87-efe9bc8cf94c
      value_template: > 
        {{ is_state('climate.tado_smart_radiator_thermostat_va0096931328', 'heat')}}
      turn_on:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va0096931328
            hvac_mode: heat
      turn_off:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va0096931328
            hvac_mode: 'off'
      icon_template: >-
        {% if is_state('climate.tado_smart_radiator_thermostat_va0096931328', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}