- platform: template
  switches:
    heating_livingroom_control_switch:
      friendly_name: 'Heating Livingroom'
      unique_id: '635d5c51-e14d-407b-93ff-1071e937f141'
      value_template: >
        {{ is_state('climate.tado_smart_radiator_thermostat_va0114429440', 'heat')}}
      turn_on:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va0114429440
            hvac_mode: heat
      turn_off:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va0114429440
            hvac_mode: 'off'
      icon_template: >-
        {% if is_state('climate.tado_smart_radiator_thermostat_va0114429440', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}