- platform: template
  switches:
    heating_toilet_tado:
      friendly_name: 'Heating Toilet'
      unique_id: 'd3a912cb-67c1-47d1-9dde-46e89abfb13c'
      turn_on:
        - service: climate.set_temperature
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va1993674240
            temperature: 25
      turn_off:
        - service: climate.set_temperature
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va1993674240
            temperature: 5