- platform: template
  switches:
    heating_toilet_control_switch:
      friendly_name: 'Heating Toilet'
      unique_id: f11622de-aac7-4cc3-b261-e5058bd411b6
      value_template: > 
        {{ is_state('climate.tado_smart_radiator_thermostat_va1993674240', 'heat')}}
      turn_on:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va1993674240
            hvac_mode: heat
      turn_off:
        - service: climate.set_hvac_mode
          data:
            entity_id: climate.tado_smart_radiator_thermostat_va1993674240
            hvac_mode: 'off'
      icon_template: >-
        {% if is_state('climate.tado_smart_radiator_thermostat_va1993674240', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}