id: '202f1c33-8ab9-44f3-8fba-d108dbd6477f'
alias: Remotec Bedroom 2 Press Button Eight 1x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "f15945068fd22bbbec21a85bf34472a2"
      property_key: "008"
      value: "KeyPressed"
action:
  - service: fan.set_percentage
    target:
      entity_id: fan.sonoff_1000cc26b0
    data:
      percentage: 100
mode: single