id: 'b16b8cde-8818-4789-a988-86b4fae61a3b'
alias: Remotec Bedroom 2 Press Button Seven 1x
initial_state: true
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: "f15945068fd22bbbec21a85bf34472a2"
      property_key: "007"
      value: "KeyPressed"
action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.bedroom_2_led
mode: single