- platform: generic_thermostat
  name: Dining Room Radiator
  unique_id: '4564bf83-0698-4d77-8ccd-146ae0b53b62'
  heater: switch.heating_dining_room_tado
  target_sensor: sensor.kitchen_dining_room_average_temperature
  min_temp: 5
  max_temp: 25
  ac_mode: false
#  cold_tolerance: 0.5
  away_temp: 5
  sleep_temp: 10