id: 'bc01f346-7f2b-4dfc-8857-48bdd019a599'
alias: Switch Christmas Livingroom
initial_state: true
description: ""
mode: single
trigger:
  - platform: time
    at: "23:59:30"
  - platform: state
    entity_id:
      - input_boolean.home_night
    to: "on"
condition:
  - condition: template
    value_template: "{{ ( now().month == 1 and now().day < 7 ) or ( now().month == 12 ) }}"
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: time
                after: "23:59:00"
              - condition: state
                entity_id: media_player.livingroom
                state: idle
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.livingroom_surge_protector_mss426_christmas_tree_lights_plug
                - switch.livingroom_surge_protector_mss426_christmas_candles_plug
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: media_player.livingroom
                state: idle
              - condition: state
                entity_id: input_boolean.home_night
                state: "on"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id:
                - switch.livingroom_surge_protector_mss426_christmas_candles_plug
                - switch.livingroom_surge_protector_mss426_christmas_tree_lights_plug