- platform: template
  covers:
    kitchen_blind:
      friendly_name: "Kitchen Blind"
      unique_id: "c1eff2fe-675d-4798-9ce7-8783f6b70d9e"
      value_template: "{{ state_attr('cover.kitchen_blind_controller_horizontal_slats_angle', 'current_tilt_position')|float > 1 }}"
      device_class: blind
      open_cover:
        - service: cover.set_cover_tilt_position
          data:
            tilt_position: 50
          target:
            entity_id: cover.kitchen_blind_controller_horizontal_slats_angle
      close_cover:
        - service: cover.set_cover_tilt_position
          data:
            tilt_position: 0
          target:
            entity_id: cover.kitchen_blind_controller_horizontal_slats_angle
      stop_cover:
        - service: cover.stop_cover
          data: {}
          target:
            entity_id: cover.kitchen_blind_controller_horizontal_slats_angle
      set_cover_position:
        - service: cover.set_cover_position 
          target:
            entity_id: cover.kitchen_blind_controller_horizontal_slats_angle
          data:
            position: "{{ position }}"