id: 'e8df5e1f-5a07-49d4-abc2-5561162b7406'
alias: Media Bedroom 3 TV Auto Off
initial_state: on
description: ""
mode: single
trigger:
  - platform: time
    at: input_datetime.bedroom_3_tv
condition: []
action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.lg_webos_tv_uk6300plb