id: '31040391-7c21-4fc4-9566-a71419979537'
alias: Security Sleep Cameras
description: ""
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm
    to: armed_night
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition: []
action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
        - switch.kitchen_privacy_mode
        - switch.livingroom_privacy_mode
