id: "dbd7d5cf-cc1d-4aec-ae88-75db12fe904c"
alias: "Notification House Water Leak"
description: ""
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.lumi_lumi_sensor_wleak_aq1_moisture
    to: "on"
condition: []
action:
  - service: script.notify_message_engine
    data:
      who: home_app
      title: "Water Leak"
      message: "{{ trigger.to_state.name }} Has detected a Water Leak"