id: '8c9b941b-1b29-40ee-9f14-2d720446a73f'
alias: Light Bathroom Brightness
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - light.bathroom_light
    to: "on"
condition: []
action:
  - service: light.turn_on 
    data_template:
      entity_id:
        - light.bathroom_light
      color_temp: >
        {% if now().hour in [22, 0, 1, 2, 3, 4, 5, 6] %} 
          496
        {% else %}
          153
        {% endif %}   
      brightness_pct: >
        {% if now().hour in [22, 0, 1, 2, 3, 4, 5, 6] %} 
          10
        {% else %}
          100
        {% endif %}
      transition: 2