id: '9b9d708f-f9df-4283-9771-93562f724253'
alias: Home Sleep Heating
description: ""
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.home_sleep
    to: "on"
condition: []
action:
  - service: climate.set_preset_mode
    data:
      preset_mode: sleep
    target:
      entity_id:
        - climate.bathroom
        - climate.bedroom_1
        - climate.living_room
        - climate.dining_room
        - climate.toilet
        - climate.hallway_2