id: '60565a07-62da-4a09-95b5-953e2ec074ec'
alias: Home Sleep Light
description: ""
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.home_sleep
    to: "on"
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: 
        - light.bedroom_2_led
        - light.bedroom_2_hyperion
        - light.bedroom_2_lamp
        - light.bedroom_2_light
        - light.bedroom_3_hyperion
        - light.bedroom_3_lamp
        - light.bedroom_3_led
        - light.bedroom_3_light
        - light.kitchen_led_strip
        - light.livingroom_lamp
        - light.livingroom_tv_led_strip