id: "289fb276-2b5b-4099-b220-8d531e3f7da0"
alias: "Home Sleep Switch"
description: ""
initial_state: true
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.home_sleep
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.home_sleep
            state: "on"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
#                - switch.kitchen_light
                - switch.diningroom_light_switch
                - switch.livingroom_1_light_switch
                - switch.livingroom_2_light_switch
                - switch.livingroom_surge_protector_outlet_5
                - switch.livingroom_surge_protector_outlet_6
                - switch.av_surge_protector_outlet_2
                - switch.av_surge_protector_outlet_3
                - switch.toilet_light_switch
                - switch.livingroom_plug_socket_4
                - switch.livingroom_plug_socket_1
                # - switch.dining_room_switch_2
                - switch.kitchen_plug_socket_3
      - conditions:
          - condition: state
            entity_id: input_boolean.home_sleep
            state: "off"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id:
                - switch.livingroom_plug_socket_4
                - switch.kitchen_plug_socket_3