id: '1231d79f-decf-465f-b760-4895c45d9ffb'
alias: Climate Bedroom 1 Fan
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: sensor.tado_smart_radiator_thermostat_va1775569408_current_temperature
condition:
    - condition: state
      entity_id: fan.sonoff_1000cc2f24
      state: 'on'
action:
    - service: fan.set_percentage
      target:
        entity_id: fan.sonoff_1000cc2f24
      data_template:
        percentage: >
          {% if states('sensor.tado_smart_radiator_thermostat_va1775569408_current_temperature') | float < 20 %}
            33
          {% elif states('sensor.tado_smart_radiator_thermostat_va1775569408_current_temperature') | float < 25 %}
            66
          {% elif states('sensor.tado_smart_radiator_thermostat_va1775569408_current_temperature') | float < 35 %}
            100
          {% endif %}