id: 'f50b9180-06ed-4426-9a48-665d9927daa6'
alias: Climate Bedroom 1 Radiator Schedule
initial_state: true
description: ""
mode: single
trigger:
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id:
      - switch.heating_bedroom_1_control_switch
    to: "on"
  - platform: state
    entity_id:
      - input_number.heating_minimum
      - input_number.heating_average
      - input_number.heating_maximum
      - input_boolean.home_away
  - platform: state
    entity_id: fan.sonoff_1000cc2f24
condition:
  - condition: state
    entity_id: switch.heating_control_switch
    state: 'on'
action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.home_home
          state: "on"
        - condition: state
          entity_id: fan.sonoff_1000cc2f24
          state: "off"
      sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.tado_smart_radiator_thermostat_va1775569408
          temperature: >
            {% if now().hour in [7, 8, 9, 10, 11, 12, 13, 14, 15, 16] %}
              {{ states('input_number.heating_average')| float(0)-2 }}
            {% elif now().hour in [6, 17, 18, 19, 20, 21, 22] %}
              {{ states('input_number.heating_maximum')| float(0)-2 }}
            {% else %}
              {{ states('input_number.heating_minimum')| float(0) }}
            {% endif %}
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.home_away
          state: "on"
        - condition: state
          entity_id: fan.sonoff_1000cc2f24
          state: "on"
      sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.tado_smart_radiator_thermostat_va1775569408
          temperature: 5