################################################################################
#
# When person 5 returns home turn on boolean input
#
################################################################################

id: '0234d51a-7b58-45af-9881-0536c20e5b75'
alias: Person 5 Returns Home
initial_state: true
trigger:
  - platform: zone
    entity_id: person.person_5
    zone: zone.home
    event: enter
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.person5_home
mode: single