id: "c75a4930-ad37-4e14-af3b-f71a5b7cdde8"
alias: "Climate Bathroom Humidity"
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.bathroom_average_humidity
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_home
        state: "on"
      - condition: state
        entity_id: input_boolean.home_sleep
        state: "off"
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.bathroom_average_humidity
            above: 75
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.bathroom_fan_switch
      - conditions:
          - condition: numeric_state
            entity_id: sensor.bathroom_average_humidity
            below: 74.9
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.bathroom_fan_switch
