id: 'd87a2c30-5f49-48a1-807a-c6983acbeefa'
alias: Climate Bathroom Radiator Schedule
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type:
      - automation_reloaded
#  - platform: time_pattern
#    minutes: /10
  - platform: state
    entity_id:
      - schedule.bathroom_thermostat_schedule
  - platform: state
    entity_id: 
      - climate.bathroom
    to: "heat"
  - platform: state
    entity_id:
      - input_number.heating_minimum
      - input_number.heating_maximum
  - platform: state
    entity_id:
      - climate.bathroom
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.bathroom
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.bathroom
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.bathroom
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: schedule.bathroom_thermostat_schedule
            state: "off"
#          - condition: not
#            conditions:
#              - condition: template
#                value_template: "{{ now().hour in [7, 18, 19, 20] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {{ states('input_number.heating_minimum')| float(0) }}
            target:
              entity_id: climate.bathroom
      - conditions:
        - condition: state
          entity_id: schedule.bathroom_thermostat_schedule
          state: "on"
#          - condition: template
#            value_template: "{{ now().hour in [7, 18, 19, 20] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {{ states('input_number.heating_maximum')| float(0) }}
            target:
              entity_id: climate.bathroom