id: "d87a2c30-5f49-48a1-807a-c6983acbeefa"
alias: "Climate Bathroom Radiator Schedule"
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - schedule.bathroom_thermostat_schedule
  - platform: state
    entity_id: 
      - climate.bathroom
    to: "heat"
  - platform: state
    entity_id:
      - sensor.heating_min
      - sensor.heating_max
    for: "00:05:00"
  - platform: state
    entity_id:
      - climate.bathroom
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.bathroom
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.bathroom
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.bathroom
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: schedule.bathroom_thermostat_schedule
            state: "off"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {% if states('sensor.heating_min') | float(0) == 5 %}
                  5
                {% else %}
                  {{ states('sensor.heating_min')| float(0)-2 }}
                {% endif %}
            target:
              entity_id: climate.bathroom
      - conditions:
        - condition: state
          entity_id: schedule.bathroom_thermostat_schedule
          state: "on"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {% if states('sensor.heating_max') | float(0) == 5 %}
                  5
                {% else %}
                  {{ states('sensor.heating_max')| float(0)-2 }}
                {% endif %}
            target:
              entity_id: climate.bathroom 