id: "9d952365-406b-4a2c-9f8f-8b52aa07de1d"
alias: "Light Kitchen Theme"
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id: sensor.hoilday_light
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.hoilday_light
            state: none
        sequence:
          - service: lifx.effect_move
            data:
              speed: 15
              direction: right
              theme: peaceful
              power_on: false
            target:
              entity_id: light.kitchen_led_strip
      - conditions:
          - condition: state
            entity_id: sensor.hoilday_light
            state: Halloween
        sequence:
          - service: lifx.effect_move
            data:
              speed: 15
              direction: right
              theme: halloween
              power_on: false
            target:
              entity_id: light.kitchen_led_strip
      - conditions:
          - condition: state
            entity_id: sensor.hoilday_light
            state: Christmas
        sequence:
          - service: lifx.effect_move
            data:
              speed: 15
              direction: right
              theme: christmas
              power_on: false
            target:
              entity_id: light.kitchen_led_strip
      - conditions:
          - condition: state
            entity_id: sensor.hoilday_light
            state: Valentine's
        sequence:
          - service: lifx.set_state
            data:
              rgb_color:
                - 255
                - 0
                - 199
            target:
              entity_id: light.kitchen_led_strip