id: '0b295924-57e6-48e3-af01-54aa8a245604'
alias: Motion Kitchen Strip
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.multisensor_6_motion_detection
condition:
  - condition: state
    entity_id: input_boolean.home_night
    state: "on"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.multisensor_6_motion_detection
            state: "on"
        sequence:
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.kitchen_led_strip
      - conditions:
          - condition: state
            entity_id: binary_sensor.multisensor_6_motion_detection
            state: "off"
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.kitchen_led_strip