id: "4fe69113-d7af-4022-8915-0266c7a0adce"
alias: "Climate Livingroom Schedule"
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - schedule.living_room_thermostat_schedule
  - platform: state
    entity_id: 
      - climate.living_room
    to: "heat"
  - platform: state
    entity_id:
      - sensor.heating_min
      - sensor.heating_max
    for: "00:05:00"
  - platform: state
    entity_id:
      - climate.living_room
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.living_room
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.living_room
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.living_room
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: schedule.living_room_thermostat_schedule
            state: "off"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {% if states('sensor.heating_min') | float(0) == 5 %}
                  5
                {% else %}
                  {{ states('sensor.heating_min')| float(0)+2 }}
                {% endif %}
            target:
              entity_id: climate.living_room
      - conditions:
        - condition: state
          entity_id: schedule.living_room_thermostat_schedule
          state: "on"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {{ states('sensor.heating_max')| float(0)+2 }}
            target:
              entity_id: climate.living_room