id: '4fe69113-d7af-4022-8915-0266c7a0adce'
alias: Climate Livingroom Schedule
initial_state: true
description: ""
mode: single
trigger:
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id:
      - switch.heating_livingroom_control_switch
    to: "on"
  - platform: state
    entity_id:
      - input_number.heating_minimum
      - input_number.heating_average
      - input_number.heating_maximum
      - input_boolean.home_away
condition:
  - condition: state
    entity_id: switch.heating_livingroom_control_switch
    state: "on"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.home_away
            state: "on"
        sequence:
          - service: climate.set_temperature
            data:
              temperature: 5
            target:
              entity_id: climate.tado_smart_radiator_thermostat_va0114429440
      - conditions:
          - condition: state
            entity_id: input_boolean.home_away
            state: "off"
          - condition: state
            entity_id: calendar.school_holidays
            state: "on"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {% if now().hour in [9, 10, 11, 13, 14, 15, 16] %}
                  {{ states('input_number.heating_average')| float(0)+2 }}
                {% elif now().hour in [8, 12, 17, 18, 19, 20, 21, 22] %}
                  {{ states('input_number.heating_maximum')| float(0)+2 }}
                {% else %}
                  {{ states('input_number.heating_minimum')| float(0) }}
                {% endif %}
            target:
              entity_id: climate.tado_smart_radiator_thermostat_va0114429440
      - conditions:
          - condition: state
            entity_id: input_boolean.home_away
            state: "off"
          - condition: state
            entity_id: calendar.school_holidays
            state: "off"
          - condition: time
            weekday:
              - mon
              - tue
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {% if now().hour in [8, 9, 10, 11, 13, 14, 15, 16] %}
                  {{ states('input_number.heating_average')| float(0)+2 }}
                {% elif now().hour in [7, 12, 17, 18, 19, 20, 21, 22] %}
                  {{ states('input_number.heating_maximum')| float(0)+2 }}
                {% else %}
                  {{ states('input_number.heating_minimum')| float(0) }}
                {% endif %}
            target:
              entity_id: climate.tado_smart_radiator_thermostat_va0114429440
      - conditions:
          - condition: state
            entity_id: input_boolean.home_away
            state: "off"
          - condition: state
            entity_id: calendar.school_holidays
            state: "off"
          - condition: time
            weekday:
              - wed
              - thu
              - fri
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {% if now().hour in [8, 9, 10, 11, 13, 14, 15, 16] %}
                  {{ states('input_number.heating_average')| float(0)+2 }}
                {% elif now().hour in [12, 17, 18, 19, 20, 21, 22] %}
                  {{ states('input_number.heating_maximum')| float(0)+2 }}
                {% else %}
                  {{ states('input_number.heating_minimum')| float(0) }}
                {% endif %}
            target:
              entity_id: climate.tado_smart_radiator_thermostat_va0114429440
      - conditions:
          - condition: state
            entity_id: input_boolean.home_away
            state: "off"
          - condition: time
            weekday:
              - sat
              - sun
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {% if now().hour in [9, 10, 11, 13, 14, 15, 16] %}
                  {{ states('input_number.heating_average')| float(0)+2 }}
                {% elif now().hour in [12, 17, 18, 19, 20, 21, 22] %}
                  {{ states('input_number.heating_maximum')| float(0)+2 }}
                {% else %}
                  {{ states('input_number.heating_minimum')| float(0) }}
                {% endif %}
            target:
              entity_id: climate.tado_smart_radiator_thermostat_va0114429440