id: '4fe69113-d7af-4022-8915-0266c7a0adce'
alias: Climate Livingroom Schedule
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type:
      - automation_reloaded
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id: 
      - climate.living_room
    to: "heat"
  - platform: state
    entity_id:
      - input_number.heating_minimum
      - input_number.heating_maximum
  - platform: state
    entity_id:
      - climate.living_room
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.living_room
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.living_room
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.living_room
action:
  - choose:
      - conditions:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ now().hour in [7, 12, 17, 18, 19, 20, 21, 22] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {{ states('input_number.heating_minimum')| float(0)+2 }}
            target:
              entity_id: climate.living_room
      - conditions:
          - condition: template
            value_template: "{{ now().hour in [7, 12, 17, 18, 19, 20, 21, 22] }}"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {{ states('input_number.heating_maximum')| float(0)+2 }}
            target:
              entity_id: climate.living_room