id: '7d548e23-bdee-4b34-b2fb-0dc81688a0b3'
alias: Climate Livingroom Radiator Warning
initial_state: true
description: ""
mode: single
trigger:
  - entity_id: binary_sensor.climate_livingroom_heating_warning
    for: 01:00:00
    platform: state
    to: 'on'
condition: []
action:
  - service: script.notify_message_engine
    data:
      who: home_app
      title: "Heating Warning"
      message: 'Warning Livingroom Radiator has been heating for 60 minutes'
  - service: climate.turn_off
    data: {}
    target:
      entity_id: climate.livingroom_radiator