id: "b9a691c3-5502-465e-87e1-54edeab0a9e4"
alias: "People Person 5 Heating"
initial_state: true
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.person5_home
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.person5_home
            state: "on"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: none
            target:
              entity_id: climate.bedroom_2
      - conditions:
          - condition: state
            entity_id: input_boolean.person5_home
            state: "off"
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: away
            target:
              entity_id: climate.bedroom_2