id: "7fee3e97-6891-4141-b643-12522f77d21a"
alias: "Alarm Clock Bedroom 1 Cover"
description: ""
initial_state: true
mode: single
trigger:
  - platform: template
    value_template: 
      "{% set alarm_time = states('sensor.bedroom_1_echo_show_next_alarm') | as_datetime %}
      {% set minutes_before = 1 %} 
      {% if alarm_time != None %}
      {{ now() >= alarm_time - timedelta(minutes = minutes_before) }}
      {% else %} 
        false 
      {% endif %}"
condition: []
action:
  - delay: 00:21:00
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.kitchen_blind