id: "e6d8aece-3176-439e-b588-4d6aeb3b1255"
alias: "Alarm Clock Bedroom 1 Set"
description: ""
initial_state: true
mode: single
trigger:
  - platform: time
    at: "01:00:00"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: person.person_2
        state: home
      - condition: state
        entity_id: sensor.bedroom_1_echo_show_next_alarm
        state: 'unknown'
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: time
                weekday:
#                  - wed
                  - thu
        sequence:
          - service: media_player.volume_mute
            data:
              is_volume_muted: true
            target:
              entity_id: media_player.bedroom_1_echo_show
          - delay: 00:01:00
          - service: media_player.play_media
            data:
              media_content_type: custom
              media_content_id: set alarm for 6:45 am
            target:
              entity_id: media_player.bedroom_1_echo_show
          - delay: 00:01:00
          - service: media_player.volume_mute
            data:
              is_volume_muted: false
            target:
              entity_id: media_player.bedroom_1_echo_show
          - delay: 00:05:00
          - service: homeassistant.reload_config_entry
            data: {}
            target:
              entity_id: media_player.bedroom_1_echo_show
      - conditions:
          - condition: and
            conditions:
              - condition: time
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
              - condition: or
                conditions:
                  - condition: state
                    entity_id: person.person_5
                    state: home
                  - condition: state
                    entity_id: person.person_4
                    state: home
              - condition: state
                entity_id: input_boolean.home_holiday
                state: "off"
        sequence:
          - service: media_player.volume_mute
            data:
              is_volume_muted: true
            target:
              entity_id: media_player.bedroom_1_echo_show
          - delay: 00:01:00
          - service: media_player.play_media
            data:
              media_content_type: custom
              media_content_id: set alarm for 6:45 am
            target:
              entity_id: media_player.bedroom_1_echo_show
          - delay: 00:01:00
          - service: media_player.volume_mute
            data:
              is_volume_muted: false
            target:
              entity_id: media_player.bedroom_1_echo_show
          - delay: 00:05:00
          - service: homeassistant.reload_config_entry
            data: {}
            target:
              entity_id: media_player.bedroom_1_echo_show