id: 'bbb74d65-1bc5-4cc7-936c-da56b4e35a77'
alias: Alarm Clock Bedroom 1 Sleep Mode
description: ""
initial_state: true
mode: single
trigger:
  - platform: time
    at: input_datetime.bedroom_1_alarm_clock
  - platform: template
    value_template: 
      "{% set alarm_time = states('sensor.bedroom_1_echo_show_next_alarm') | as_datetime %}
      {% set minutes_before = 1 %} 
      {% if alarm_time != None %}
      {{ now() >= alarm_time - timedelta(minutes = minutes_before) }}
      {% else %} 
        False 
      {% endif %}"
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.home_sleep