id: "bbb74d65-1bc5-4cc7-936c-da56b4e35a77"
alias: "Alarm Clock Bedroom 1 Sleep Mode"
description: ""
initial_state: true
mode: single
trigger:
  - platform: time
    at: "09:00:00"
  - platform: template
    value_template: 
      "{% set alarm_time = states('sensor.bedroom_1_echo_show_next_alarm') | as_datetime %}
      {% set minutes_before = 1 %} 
      {% if alarm_time != none %}
      {{ now() >= alarm_time - timedelta(minutes = minutes_before) }}
      {% else %} 
        False 
      {% endif %}"
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.home_sleep
  - delay: 00:21:00
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: media_player.bedroom_1_echo_show