- platform: template
  switches:
    bedroom_3_tv:
      friendly_name: "Bedroom 3 TV"
      unique_id: "ceb6967b-758c-4441-aeb7-9544a4355920"
      value_template: >-
        {{ is_state('media_player.lg_webos_tv_uk6300plb', 'on')}}
      turn_on:
        - service: remote.send_command
          entity_id: remote.bedroom_3_rm_remote_remote
          data:
            device: tv
            command: power
      turn_off:
        - service: remote.send_command
          entity_id: remote.bedroom_3_rm_remote_remote
          data:
            device: tv
            command: power