id: "a51bce11-75a4-447d-b1e5-6f7421e5f1b4"
alias: "Climate Dining Room Schedule"
initial_state: true
description: ""
mode: single
trigger:
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - schedule.dinning_room_schedule
  - platform: state
    entity_id: 
      - climate.dining_room
    to: "heat"
  - platform: state
    entity_id:
      - sensor.heating_min
      - sensor.heating_max
    for: "00:05:00"
  - platform: state
    entity_id:
      - climate.bathroom
    attribute: preset_mode
    to: none
  - platform: state
    entity_id:
      - climate.dining_room
    from: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.dining_room
        state: "heat"
      - condition: state
        state: "none"
        attribute: preset_mode
        entity_id: climate.dining_room
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: schedule.dinning_room_schedule
            state: "off"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: > 
                {% if states('sensor.heating_min') | float(0) == 5 %}
                  5
                {% else %}
                  {{ states('sensor.heating_min')| float(0) }}
                {% endif %}
            target:
              entity_id: climate.dining_room
      - conditions:
        - condition: state
          entity_id: schedule.dinning_room_schedule
          state: "on"
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: >
                {% if states('sensor.heating_max') | float(0) == 5 %}
                  5
                {% else %}
                  {{ states('sensor.heating_max')| float(0) }}
                {% endif %}
            target:
              entity_id: climate.dining_room