id: "db39733b-e28a-4c6b-9803-d20dbf00d3bb"
alias: "Notification CR1632 Battery Low"
description: ""
initial_state: true
mode: single
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.lumi_lumi_motion_ac02_battery
    below: 10
    for: "00:30:00"
condition: []
action:
  - service: script.notify_message_engine
    data:
      who: home_app
      title: "CR1632 Battery Low"
      message: "{{ trigger.to_state.name }} Battery Low"